services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/investment-tracker
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo_data:
