services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "1.0"
          memory: 4G

networks:
  mynetwork:
    driver: bridge
