services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - mynetwork
     dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 8G
        reservations:
          cpus: "1.0"
          memory: 4G

networks:
  mynetwork:
    driver: bridge
