services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PUPPETEER_CACHE_DIR=/app/.cache/puppeteer
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    volumes:
      - puppeteer_cache:/app/.cache/puppeteer
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512M
        reservations:
          cpus: "1.0"
          memory: 4G

networks:
  mynetwork:
    driver: bridge

volumes:
  puppeteer_cache:
