services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/investment-tracker
    depends_on:
      - mongo
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "4.0" # 2 CPUs
          memory: 8G # 4 GB RAM
        reservations:
          cpus: "2.0" # Reserve 1 CPU
          memory: 4G # Reserve 2 GB RAM

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "0.5" # 0.5 CPU
          memory: 1G # 1 GB RAM

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo_data:
